### ISSUE TITLE
Null safety not supported

### ISSUE THREAD

**Issue by zhpixel517** [cunarist/rinf#254]
## Report

I just tried to install rinf for the first time and get it set up and I'm met with this warning:

```
The lower bound of "sdk: '>=2.10.0 <3.0.0'" must be 2.12.0'
or higher to enable null safety.

The current Dart SDK (3.1.2) only supports null safety.

For details, see https://dart.dev/null-safety
```

## Steps to Reproduce

All I did was `cargo install rinf` and then typed `rinf`

## System Information

```bash
rustc --version
protoc --version
flutter doctor
```

`rustc 1.74.1 (a28077b28 2023-12-04)`
`libprotoc 25.1`
```
[✓] Flutter (Channel stable, 3.13.4, on macOS 14.2.1 23C71 darwin-arm64, locale
    en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.85.1)
[✓] Connected device (3 available)            
[✓] Network resources

• No issues found!
```

**Comment by temeddix** [comment]
Hi @zhpixel517 , thanks for the report! I'm currently too busy to fix all these issues, but still am open to accepting PRs. I will try to fix this as soon as I get free :)

**Comment by temeddix** [comment]
This is Rinf's `pubspec.yaml`

```yaml
name: rinf
description: Rust for native business logic, Flutter for flexible and beautiful GUI
version: 5.2.0
repository: https://github.com/cunarist/rinf

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.3.0"
```

We require Dart 3.0.5 or higher, so it doesn't look like a problem with Rinf. Could you check if your project it set to require higher version of Dart?

- https://dart.dev/null-safety/migration-guide
